version: '2'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    #pro vyvoj - override
    #volumes:
      #- .:/app
    #pro vyvoj
    #entrypoint: ./mvnw spring-boot:run
  db:
    ports:
      - "3306:3306"
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=<password>